print("Enter your first number")
number1=int(input())
print("Enter your second number")
number2=int(input())
print("Addition is performed                            ",number1 + number2)
print("Multiplication is performed                      ",number1 * number2)
print("Subtraction is performed                         ",number1 - number2)
print("Division is performed                            ",number1 / number2)
print("Double Devision is performed                     ",number1 // number2)
print("Modulus is performed                             ",number1 % number2)
print("Right shift operation is performed               ",number1 >> number2)
print("Left shift opetation is performed                ",number1 << number2)
print("Bitwise & And operation is performed             ",number1 & number2)
print("Bitwise | or operation is performed              ",number1 | number2)
print("Bitwise ^ Exclusive Or operation is performed    ",number1 ^ number2)
print("Bitwise ~ XOR operation is performed             ",number1 != number2)