# print("Enter first number")
# first=int(input())
# print("Enter second number")
# second = int(input())
# print("result will be ",(first+second))
# var=float(input())
# print(var)

#include
# print(input())
print("Enter first number")
inp1=input()
print("Enter second number")
inp2=input()

print("\n")
#
# print("Performing All Arithmatic Operations in both the number")
# print("All the Operation is performing without converting into int")
# print("Addition  ",inp1 + inp2)
# # print("Subtraction ",inp1 - inp2)
# # print("Division  ",inp1 / inp2)
# # print("Double Division  ",inp1 // inp2)
# # print("Multiplication   ",inp1 * inp2)
# # print("Modulus  ",inp1 % inp2)

#-------------------------------------------------------------------
print("Performing All Arithmatic Operations in both the number")
print("All the Operation is performing without converting into int")
print("Addition  ",int(inp1) + int(inp2))
print("Subtraction ",int(inp1) - int(inp2))
print("Division  ",int(inp1) / int(inp2))
print("Double Division  ",int(inp1) // int(inp2))
print("Multiplication   ",int(inp1) * int(inp2))
print("Modulus  ",int(inp1) % int(inp2))